$root = (Get-Location).Path

New-Item -ItemType Directory -Force -Path "$root\api\trpc" | Out-Null
$b = [System.Convert]::FromBase64String("aW1wb3J0IHR5cGUgeyBWZXJjZWxSZXF1ZXN0LCBWZXJjZWxSZXNwb25zZSB9IGZyb20gIkB2ZXJjZWwvbm9kZSI7CmltcG9ydCB7IGZldGNoUmVxdWVzdEhhbmRsZXIgfSBmcm9tICJAdHJwYy9zZXJ2ZXIvYWRhcHRlcnMvZmV0Y2giOwppbXBvcnQgeyBhcHBSb3V0ZXIgfSBmcm9tICIuLi8uLi9zZXJ2ZXIvcm91dGVycyI7CmltcG9ydCB7IGNyZWF0ZUNvbnRleHQgfSBmcm9tICIuLi8uLi9zZXJ2ZXIvX2NvcmUvY29udGV4dCI7CgpleHBvcnQgY29uc3QgY29uZmlnID0gewogIG1heER1cmF0aW9uOiAzMCwKfTsKCmV4cG9ydCBkZWZhdWx0IGFzeW5jIGZ1bmN0aW9uIGhhbmRsZXIoCiAgcmVxOiBWZXJjZWxSZXF1ZXN0LAogIHJlczogVmVyY2VsUmVzcG9uc2UsCikgewogIC8vIENvbnZlcnQgVmVyY2VsJ3MgSW5jb21pbmdNZXNzYWdlIHRvIGEgV2ViIEFQSSBSZXF1ZXN0IGZvciBmZXRjaFJlcXVlc3RIYW5kbGVyCiAgY29uc3QgdXJsID0gYGh0dHBzOi8vJHtyZXEuaGVhZGVyc1siaG9zdCJdID8/ICJsb2NhbGhvc3QifSR7cmVxLnVybCA/PyAiLyJ9YDsKCiAgY29uc3QgaGVhZGVycyA9IG5ldyBIZWFkZXJzKCk7CiAgZm9yIChjb25zdCBba2V5LCB2YWx1ZV0gb2YgT2JqZWN0LmVudHJpZXMocmVxLmhlYWRlcnMpKSB7CiAgICBpZiAodmFsdWUgPT09IHVuZGVmaW5lZCkgY29udGludWU7CiAgICBpZiAoQXJyYXkuaXNBcnJheSh2YWx1ZSkpIHsKICAgICAgdmFsdWUuZm9yRWFjaCgodikgPT4gaGVhZGVycy5hcHBlbmQoa2V5LCB2KSk7CiAgICB9IGVsc2UgewogICAgICBoZWFkZXJzLnNldChrZXksIHZhbHVlKTsKICAgIH0KICB9CgogIGxldCBib2R5SW5pdDogQm9keUluaXQgfCB1bmRlZmluZWQ7CiAgaWYgKHJlcS5tZXRob2QgIT09ICJHRVQiICYmIHJlcS5tZXRob2QgIT09ICJIRUFEIikgewogICAgYm9keUluaXQgPSBKU09OLnN0cmluZ2lmeShyZXEuYm9keSk7CiAgfQoKICBjb25zdCByZXF1ZXN0ID0gbmV3IFJlcXVlc3QodXJsLCB7CiAgICBtZXRob2Q6IHJlcS5tZXRob2QgPz8gIkdFVCIsCiAgICBoZWFkZXJzLAogICAgYm9keTogYm9keUluaXQsCiAgfSk7CgogIGNvbnN0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2hSZXF1ZXN0SGFuZGxlcih7CiAgICBlbmRwb2ludDogIi9hcGkvdHJwYyIsCiAgICByZXE6IHJlcXVlc3QsCiAgICByb3V0ZXI6IGFwcFJvdXRlciwKICAgIGNyZWF0ZUNvbnRleHQ6IGFzeW5jICgpID0+CiAgICAgIGNyZWF0ZUNvbnRleHQoewogICAgICAgIHJlcTogcmVxIGFzIGFueSwKICAgICAgICByZXM6IHJlcyBhcyBhbnksCiAgICAgICAgaW5mbzogeyBpc0JhdGNoQ2FsbDogZmFsc2UsIGNhbGxzOiBbXSB9IGFzIGFueSwKICAgICAgfSksCiAgICBvbkVycm9yKHsgZXJyb3IsIHBhdGggfSkgewogICAgICBpZiAoZXJyb3IuY29kZSA9PT0gIklOVEVSTkFMX1NFUlZFUl9FUlJPUiIpIHsKICAgICAgICBjb25zb2xlLmVycm9yKGBbdFJQQ10gRXJyb3Igb24gJHtwYXRoID8/ICJ1bmtub3duIn06YCwgZXJyb3IpOwogICAgICB9CiAgICB9LAogIH0pOwoKICAvLyBDb3B5IHJlc3BvbnNlIGhlYWRlcnMKICByZXNwb25zZS5oZWFkZXJzLmZvckVhY2goKHZhbHVlLCBrZXkpID0+IHsKICAgIHJlcy5zZXRIZWFkZXIoa2V5LCB2YWx1ZSk7CiAgfSk7CgogIGNvbnN0IGJvZHkgPSBhd2FpdCByZXNwb25zZS50ZXh0KCk7CiAgcmVzLnN0YXR1cyhyZXNwb25zZS5zdGF0dXMpLnNlbmQoYm9keSk7Cn0K")
[System.IO.File]::WriteAllBytes("$root\api\trpc\[trpc].ts", $b)
Write-Host "  OK api\trpc\[trpc].ts" -ForegroundColor Green

New-Item -ItemType Directory -Force -Path "$root\shared" | Out-Null
$b = [System.Convert]::FromBase64String("ewogICJuYW1lIjogIkBzaGFyZWQiLAogICJ2ZXJzaW9uIjogIjEuMC4wIiwKICAidHlwZSI6ICJtb2R1bGUiLAogICJleHBvcnRzIjogewogICAgIi4vKiI6ICIuLyoudHMiCiAgfQp9Cg==")
[System.IO.File]::WriteAllBytes("$root\shared\package.json", $b)
Write-Host "  OK shared\package.json" -ForegroundColor Green

Write-Host ""
Write-Host "Pronto! Agora rode:" -ForegroundColor Cyan
Write-Host "  git add -A"
Write-Host "  git commit -m fix2"
Write-Host "  git push"