$root = (Get-Location).Path

$b = [System.Convert]::FromBase64String("aW1wb3J0IHsgYnVpbGQgfSBmcm9tICdlc2J1aWxkJzsKaW1wb3J0IHsgZ2xvYiB9IGZyb20gJ2dsb2InOwppbXBvcnQgcGF0aCBmcm9tICdwYXRoJzsKaW1wb3J0IHsgZmlsZVVSTFRvUGF0aCB9IGZyb20gJ3VybCc7Cgpjb25zdCByb290ID0gcGF0aC5kaXJuYW1lKGZpbGVVUkxUb1BhdGgoaW1wb3J0Lm1ldGEudXJsKSk7CmNvbnN0IGVudHJ5UG9pbnRzID0gYXdhaXQgZ2xvYignYXBpLyoqLyoudHMnLCB7IGN3ZDogcm9vdCB9KTsKCmNvbnNvbGUubG9nKCdbYnVpbGQtYXBpXSBCdW5kbGluZycsIGVudHJ5UG9pbnRzLmxlbmd0aCwgJ2Z1bmN0aW9ucy4uLicpOwoKYXdhaXQgYnVpbGQoewogIGVudHJ5UG9pbnRzOiBlbnRyeVBvaW50cy5tYXAoZSA9PiBwYXRoLmpvaW4ocm9vdCwgZSkpLAogIGJ1bmRsZTogdHJ1ZSwKICBwbGF0Zm9ybTogJ25vZGUnLAogIHRhcmdldDogJ25vZGUyMCcsCiAgZm9ybWF0OiAnZXNtJywKICBvdXRkaXI6IHBhdGguam9pbihyb290LCAnYXBpJyksCiAgb3V0YmFzZTogcGF0aC5qb2luKHJvb3QsICdhcGknKSwKICBleHRlcm5hbDogWwogICAgJ0BsaWJzcWwvY2xpZW50JywKICAgICdAbGlic3FsLyonLAogICAgJ215c3FsMicsCiAgICAnanNkb20nLAogICAgJ2NhbnZhcycsCiAgXSwKICBhbGlhczogewogICAgJ0BzaGFyZWQnOiBwYXRoLmpvaW4ocm9vdCwgJ3NoYXJlZCcpLAogIH0sCiAgbG9nTGV2ZWw6ICdpbmZvJywKfSk7Cgpjb25zb2xlLmxvZygnW2J1aWxkLWFwaV0gRG9uZSEnKTsK")
[System.IO.File]::WriteAllBytes("$root\build-api.mjs", $b)
Write-Host "OK build-api.mjs (output em api/)" -ForegroundColor Green

$b = [System.Convert]::FromBase64String("ewogICJ2ZXJzaW9uIjogMiwKICAiYnVpbGRDb21tYW5kIjogInBucG0gaW5zdGFsbCAmJiBub2RlIGJ1aWxkLWFwaS5tanMgJiYgdml0ZSBidWlsZCIsCiAgImluc3RhbGxDb21tYW5kIjogInBucG0gaW5zdGFsbCIsCiAgImZyYW1ld29yayI6IG51bGwsCiAgIm91dHB1dERpcmVjdG9yeSI6ICJkaXN0IiwKICAiZnVuY3Rpb25zIjogewogICAgImFwaS8qKi8qLmpzIjogewogICAgICAicnVudGltZSI6ICJAdmVyY2VsL25vZGVANS4wLjAiCiAgICB9CiAgfSwKICAicmV3cml0ZXMiOiBbCiAgICB7CiAgICAgICJzb3VyY2UiOiAiL2FwaS90cnBjLzpwYXRoKiIsCiAgICAgICJkZXN0aW5hdGlvbiI6ICIvYXBpL3RycGMvW3RycGNdIgogICAgfSwKICAgIHsKICAgICAgInNvdXJjZSI6ICIvYXBpL2F1dGgvOnBhdGgqIiwKICAgICAgImRlc3RpbmF0aW9uIjogIi9hcGkvYXV0aC9bYXV0aF0iCiAgICB9LAogICAgewogICAgICAic291cmNlIjogIi9hcGkvb2F1dGgvOnBhdGgqIiwKICAgICAgImRlc3RpbmF0aW9uIjogIi9hcGkvb2F1dGgvW29hdXRoXSIKICAgIH0sCiAgICB7CiAgICAgICJzb3VyY2UiOiAiL2FwaS9zdHJpcGUvOnBhdGgqIiwKICAgICAgImRlc3RpbmF0aW9uIjogIi9hcGkvc3RyaXBlL1tzdHJpcGVdIgogICAgfSwKICAgIHsKICAgICAgInNvdXJjZSI6ICIvKC4qKSIsCiAgICAgICJkZXN0aW5hdGlvbiI6ICIvaW5kZXguaHRtbCIKICAgIH0KICBdLAogICJjcm9ucyI6IFsKICAgIHsKICAgICAgInBhdGgiOiAiL2FwaS9jcm9uL2NsZWFudXAiLAogICAgICAic2NoZWR1bGUiOiAiMCAzICogKiAqIgogICAgfQogIF0KfQo=")
[System.IO.File]::WriteAllBytes("$root\vercel.json", $b)
Write-Host "OK vercel.json (functions: api/**/*.js)" -ForegroundColor Green

git add -A
git commit -m "fix: esbuild compila api/*.ts para api/*.js no mesmo diretório"
git push origin main
Write-Host "Deploy disparado!" -ForegroundColor Green
